tunnel: 56c84116-0ef0-47c7-bbea-25634d765487
credentials-file: /Users/jambimac/.cloudflared/56c84116-0ef0-47c7-bbea-25634d765487.json

ingress:
  - hostname: trading.jbrasfield.com
    service: http://localhost:8888
  - service: http_status:404
